CREATE TABLE [dbo].[UserTenantRole] (
    [UserUID]   UNIQUEIDENTIFIER NOT NULL,
    [TenantUID] UNIQUEIDENTIFIER NOT NULL,
    [RoleUID]   UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_UserTenantRole] PRIMARY KEY CLUSTERED ([UserUID] ASC, [TenantUID] ASC, [RoleUID] ASC)
);

